import type { DitherOptions } from "../../types";

/**
 * Produce the source text of a standalone, dependency-free ES module that
 * reproduces this dither pass — the "Reusable JS filter" export. `options` are
 * baked in as `DEFAULT_BAYER_OPTIONS`.
 */
export function reusableModuleSource(options: DitherOptions): string {
  const defaults = JSON.stringify(options, null, 2);
  return `/** Bayer ordered-dither filter generated by Bayer Studio. */
export const DEFAULT_BAYER_OPTIONS = ${defaults};

export function makeBayerMatrix(size = 8) {
  if (![2, 4, 8, 16].includes(size)) throw new RangeError('Bayer size must be 2, 4, 8, or 16.');
  let matrix = [[0, 2], [3, 1]], current = 2;
  while (current < size) {
    const next = Array.from({ length: current * 2 }, () => Array(current * 2).fill(0));
    for (let y = 0; y < current; y++) for (let x = 0; x < current; x++) {
      const value = matrix[y][x] * 4;
      next[y][x] = value; next[y][x + current] = value + 2;
      next[y + current][x] = value + 3; next[y + current][x + current] = value + 1;
    }
    matrix = next; current *= 2;
  }
  return matrix;
}
const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, v));
const parseHex = (value) => {
  const hex = value.replace(/^#/, '');
  if (/^[0-9a-f]{3}$/i.test(hex)) return [...hex].map(c => parseInt(c + c, 16));
  if (/^[0-9a-f]{6}$/i.test(hex)) return [0,2,4].map(i => parseInt(hex.slice(i, i + 2), 16));
  throw new TypeError('Invalid hex color: ' + value);
};
const parsePalette = (value) => String(value).split(/[\\s,;]+/).filter(Boolean).map(parseHex);
const nearest = (r,g,b,palette) => palette.reduce((best,c) => {
  const d=(r-c[0])**2+(g-c[1])**2+(b-c[2])**2;
  return d < best.d ? { c, d } : best;
}, { c: palette[0], d: Infinity }).c;
const quantize = (value, levels, threshold) => {
  const scaled=clamp(value,0,1)*(levels-1), low=Math.floor(scaled);
  return Math.min(levels-1, low + ((scaled-low)>=threshold ? 1 : 0))/(levels-1);
};

/** Mutates and returns an ImageData object. */
export function ditherImageData(imageData, custom = {}) {
  const o = { ...DEFAULT_BAYER_OPTIONS, ...custom };
  const matrix=makeBayerMatrix(Number(o.matrixSize)), n=matrix.length, denominator=n*n;
  const levels=clamp(Math.round(o.levels),2,32), dark=parseHex(o.dark), light=parseHex(o.light);
  const palette=parsePalette(o.palette); if (palette.length < 2) throw new RangeError('Palette needs at least two colors.');
  const data=imageData.data, pattern=Math.max(1,Math.round(o.patternScale));
  for (let y=0;y<imageData.height;y++) for (let x=0;x<imageData.width;x++) {
    const i=(y*imageData.width+x)*4; if (!data[i+3]) continue;
    const ordered=(matrix[Math.floor(y/pattern)%n][Math.floor(x/pattern)%n]+.5)/denominator;
    const threshold=clamp(.5+(ordered-.5)*o.strength+o.bias,0,1);
    let r=data[i]/255,g=data[i+1]/255,b=data[i+2]/255;
    const l=.2126*r+.7152*g+.0722*b;
    r=clamp((l+(r-l)*o.saturation-.5)*o.contrast+.5,0,1);
    g=clamp((l+(g-l)*o.saturation-.5)*o.contrast+.5,0,1);
    b=clamp((l+(b-l)*o.saturation-.5)*o.contrast+.5,0,1);
    r=Math.pow(r,o.gamma); g=Math.pow(g,o.gamma); b=Math.pow(b,o.gamma);
    if (o.mode === 'mono' || o.mode === 'gray') {
      const q=quantize(.2126*r+.7152*g+.0722*b,o.mode==='mono'?2:levels,threshold);
      if (o.mode === 'mono') { data[i]=dark[0]+(light[0]-dark[0])*q; data[i+1]=dark[1]+(light[1]-dark[1])*q; data[i+2]=dark[2]+(light[2]-dark[2])*q; }
      else data[i]=data[i+1]=data[i+2]=Math.round(Math.pow(q,1/o.gamma)*255);
    } else if (o.mode === 'palette') {
      const p=(ordered-.5)*o.strength*255+o.bias*255, c=nearest(clamp(r*255+p,0,255),clamp(g*255+p,0,255),clamp(b*255+p,0,255),palette);
      data[i]=c[0]; data[i+1]=c[1]; data[i+2]=c[2];
    } else {
      data[i]=Math.round(Math.pow(quantize(r,levels,threshold),1/o.gamma)*255);
      data[i+1]=Math.round(Math.pow(quantize(g,levels,threshold),1/o.gamma)*255);
      data[i+2]=Math.round(Math.pow(quantize(b,levels,threshold),1/o.gamma)*255);
    }
  }
  return imageData;
}
`;
}
